services:
  localstack:
    image: localstack/localstack-pro
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    env_file:
      - .env
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack:/etc/localstack"
      - "./localstack-data:/var/lib/localstack"